### ISSUE TITLE
Audience for this project?

### ISSUE THREAD

**Issue by adamretter** [EugenMayer/nist-data-mirror#2]
We were using https://github.com/stevespringett/nist-data-mirror but it is now archived as it does not support the NIST v2 API.

I see you have the most recently worked on fork, is your fork intended to be used by others? Do you have any plans to support the v2 API, or would you accept PRs to do so?

In short, can we consider your fork a replacement for tevespringett/nist-data-mirror ?

Kind regards.

**Comment by EugenMayer** [comment]
@adamretter yes it is inteded to be used by others free of anything. 

> In short, can we consider your fork a replacement for tevespringett/nist-data-mirror ?

By no means "official", i'am just a user that wants the mirror to live on and will maintain it. We do run this in production, so be invited to do so also

**Comment by adamretter** [comment]
> Do you have any plans to support the v2 API, or would you accept PRs to do so?

**Comment by EugenMayer** [comment]
@adamretter i for sure would love to switch and support to v2 - if you have something to review, i'am happy to do so!

**Comment by EugenMayer** [comment]
@adamretter shall i close this issue or are you going to work on the v2 API? just let me know
